/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package uk.co.kleindelao.ecf.clubratings.app

fun main() {
//    val tokens = StringUtils.split(MessageUtils.getMessage())
//    val result = StringUtils.join(tokens)
//    println(WordUtils.capitalize(result))
}
