/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.co.kleindelao.ecf.clubratings.kotlin-application-conventions")
}

dependencies {
    project(":domain-model")
    implementation("org.apache.commons:commons-text")
    testImplementation("org.assertj:assertj-core")
}

application {
    // Define the main class for the application.
    mainClass.set("uk.co.kleindelao.ecf.clubratings.app.AppKt")
}
