/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.14.0")
        implementation("org.jsoup:jsoup:1.21.1")
        implementation("com.squareup.okhttp:okhttp:2.7.5")
        testImplementation("org.assertj:assertj-core:3.27.3")
        implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.19.2")
        implementation("com.giffing.wicket.spring.boot.starter:wicket-spring-boot-starter:4.0.0")
        implementation("org.apache.wicket:wicket-extensions:10.6.0")
    }
}

kotlin {
    jvmToolchain(17)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.1")
        }
    }
}
